# Generated by Django 4.2.3 on 2023-07-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cateogry',
            new_name='category',
        ),
    ]
